name: Daily Commit

on:
  workflow_dispatch:  # Allows manual triggering
  schedule:
    - cron: '*/1 * * * *' 

jobs:
  daily-commit:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Create or update daily log
        run: |
          echo "Daily commit on $(date)" >> daily_log.txt

      - name: Commit and Push Changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --local user.email "lizayakimenka@gmail.com"
          git config --local user.name "lizaveta-yakimenka"
          git add daily_log.txt
          git commit -m "Daily commit on $(date)" || echo "No changes to commit"
          git push origin main 
